//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.30 at 11:27:19 AM CEST 
//


package com.o3.storyinspector.storydom;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Locations"/&gt;
 *         &lt;element ref="{}Characters"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="wordCount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sentimentScore" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fkGrade" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "locations",
    "characters"
})
@XmlRootElement(name = "Metadata")
public class Metadata
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "Locations", required = true)
    protected Locations locations;
    @XmlElement(name = "Characters", required = true)
    protected Characters characters;
    @XmlAttribute(name = "wordCount")
    protected String wordCount;
    @XmlAttribute(name = "sentimentScore")
    protected String sentimentScore;
    @XmlAttribute(name = "fkGrade")
    protected BigDecimal fkGrade;

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link Locations }
     *     
     */
    public Locations getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Locations }
     *     
     */
    public void setLocations(Locations value) {
        this.locations = value;
    }

    /**
     * Gets the value of the characters property.
     * 
     * @return
     *     possible object is
     *     {@link Characters }
     *     
     */
    public Characters getCharacters() {
        return characters;
    }

    /**
     * Sets the value of the characters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Characters }
     *     
     */
    public void setCharacters(Characters value) {
        this.characters = value;
    }

    /**
     * Gets the value of the wordCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWordCount() {
        return wordCount;
    }

    /**
     * Sets the value of the wordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWordCount(String value) {
        this.wordCount = value;
    }

    /**
     * Gets the value of the sentimentScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentimentScore() {
        return sentimentScore;
    }

    /**
     * Sets the value of the sentimentScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentimentScore(String value) {
        this.sentimentScore = value;
    }

    /**
     * Gets the value of the fkGrade property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFkGrade() {
        return fkGrade;
    }

    /**
     * Sets the value of the fkGrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFkGrade(BigDecimal value) {
        this.fkGrade = value;
    }

}
